name: Continuous Integration and Deployment
on:
  push:
     branches: [master]
  pull_request: 
     branches: [master]


jobs:
  build:
    runs-on: self-hosted
    
 
    steps:
      - name: Display contents of directory before checkout
        run: |
          echo "Before checkout:"
          ls -la
      #- name: Copy .env
        #run: |
          #cp -a -r ecosystem.config.js ./../tmp/
      - name: Checkout code
        uses: actions/checkout@v3

    
      - name: Display contents of directory after checkout
        run: |
          echo "After checkout:"
          ls -la

      - name: Uses Node.js ${{ matrix.version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      

      #- name: Build React App
        #run: |
          #CI=false npm run build

      #- name: Copy build files to target path
        #run: |
          #cp -r build/* ./../../../../public_html/

      - name: Move Files Back
        run: |
          cp -a -r ./../tmp/ecosystem.config.js .

      - name: Reload and save PM2 configuration
        run: |
          pm2 reload ecosystem.config.js
          pm2 save 
